### PR TITLE
added python 3.7 to travis CI

### PR DESCRIPTION
**Pull request by gdementen**

### CODE REVIEW

**Comment by gdementen** [comment]
apparently pytest-pep8 is not yet available for python3.7

**Comment by alixdamman** [comment]
So, we need to add something like

```bash
if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then
        conda install pytest-pep8
fi
```

**Comment by gdementen** [comment]
duh? this will fail too?!?

**Comment by gdementen** [comment]
@alixdamman thanks for the info :)

**Pull request merged**
