### PR TITLE
issue 737 : cleanup modules namespaces

### PR DESCRIPTION
**Pull request by alixdamman**

### CODE REVIEW

**Comment by alixdamman** [comment]
What do you mean by "all public API is still exposed"?

**Comment by alixdamman** [comment]
OK to merge?

**Comment by gdementen** [comment]
> What do you mean by "all public API is still exposed"?

That everything which was supposed to be in the top level namespace (not included by accident) still is.
  
> OK to merge?

Sure

**Comment by alixdamman** [comment]
PR #710 will help to know if something is missing

**Pull request merged**
