### PR TITLE
misc fixes & comments

### PR DESCRIPTION
**Pull request by gdementen**

### CODE REVIEW

**Comment by alixdamman** [comment]
LGTM

**Comment by alixdamman** [comment]
in file `setup.cfg`, there is a commented option to ask pytest to also test PEP8 compliance. 
Do you want to unlock this option?

**Comment by gdementen** [comment]
> in file setup.cfg, there is a commented option to ask pytest to also test PEP8 compliance.
Do you want to unlock this option?

It is worth a try... Depends if we can configure some of it (for example 120 char lines -- otherwise we will be swamped in messages) and if there are not too many false positives.

**Comment by alixdamman** [comment]
Yes, you can change the maximum number of characters per line: `pep8maxlinelength = 119` (already in `setup.cfg`). For the other options, I don't know. Examples are given here: https://pypi.org/project/pytest-pep8/

**Pull request merged**
